services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp

  grafana-dev:
    image: ghcr.io/volkovlabs/app:latest@sha256:7255f71881b7aa94198da4760a3c74fbbc5f6d16b592ec55f69c40c4e479b7be
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-variable-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  timescale:
    image: timescale/timescaledb:latest-pg14@sha256:0f5553d37abbe0f20bfe0a04dab5d1238955b5cda2711aba403090f95b6e51ff
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./timescale:/docker-entrypoint-initdb.d
    profiles:
      - dev
      - main
      - dependency
      - playwright

  server:
    build:
      context: ./timescale
    ports:
      - 3001:3001/tcp
    depends_on:
      - timescale
    environment:
      WAIT_HOSTS: timescale:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: timescale
    profiles:
      - dev
      - main
      - dependency
      - playwright

  grafana-main:
    image: grafana/grafana:main@sha256:551dc4bc2c3b057f8c50de2ac98451b5ea79fe1d7ca76ed03c3931b1105c4122
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-variable-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.5.0@sha256:0a2874cf39c6487093c682215f7c7903ed8646d78ae5f911af945d2dfcc0a447
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-variable-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      - grafana
      - timescale
      - server
    profiles:
      - playwright
